default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: obraz_development
  username: obraz

test:
  <<: *default
  database: obraz_test

production:
  <<: *default
  database: obraz_production
  username: obraz
  password: <%= ENV['OBRAZ_DATABASE_PASSWORD'] %>
